### ISSUE TITLE
换了样本训练时报错IndexError: row index (2231) out of range

### ISSUE THREAD

**Issue by NewCrazyStone** [Coldwave96/MaliciousUrls_Part2#3]
![image](https://user-images.githubusercontent.com/24403973/156141747-4aefbf91-2746-495d-bf0a-39ec1fb8cdb7.png)

**Comment by Coldwave96** [comment]
你需要改下model.py的代码逻辑，用你的样本重新训练模型。目前的代码逻辑是直接调用已有的训练好的模型。

**Comment by NewCrazyStone** [comment]
大佬，具体改什么地方，请教一下

**Comment by Coldwave96** [comment]
你是不是model文件夹里的文件没删掉，pickle文件是模型，lable文件是预处理的特征都要删。

**Comment by NewCrazyStone** [comment]
删了之后训练就会报这个错
![image](https://user-images.githubusercontent.com/24403973/156145416-fb1386f0-1f7c-4e63-ac6b-a9911d04c41b.png)

**Comment by NewCrazyStone** [comment]
找到问题了，k80.label文件不要删，里面的内容清空就可以了，多谢大佬指点

**Comment by Coldwave96** [comment]
cool
